# Generated by Django 3.1.2 on 2020-10-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('CAT', 'cat'), ('DOG', 'dog'), ('PARROT', 'parrot'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=7),
        ),
    ]
