# Generated by Django 3.1.2 on 2020-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201027_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='test',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
