# Generated by Django 3.1.2 on 2020-10-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('PARROT', 'Parrot'), ('UNKNOWN', 'Unknown')], default='Unknown', max_length=7),
        ),
    ]
