# Generated by Django 3.1.2 on 2020-10-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20201030_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
